#!/bin/bash

# For updates and backups
alias upd='sudo apt update;sudo apt upgrade;ws-gitNotes;ws-gitWS'

# Shortcuts
alias ai='ollama run llama3.2 $1'

# For navigating to different dir
alias dk="cd ~/Desktop"
alias ws='cd ~/ws'

# For python virtual env activation and deactivation
alias venv="source ~/venv/bin/activate"
alias denv="deactivate"

# Networking
alias ipShow="hostname -I | awk '{print \$1}'"
alias goLive='python3 -m http.server $1'
alias portCheck='nmap localhost'
