#!/bin/bash

# For updates and backups
alias ws-upd='sudo apt update;sudo apt upgrade;ws-gitNotes;ws-gitWS'

# Shortcuts
alias ws-ai='ollama run llama3.2 $1'

# For navigating to different dir
alias dk="cd ~/Desktop"
alias ws='cd ~/ws'

# For python virtual env activation and deactivation
alias ws-venv="source ~/venv/bin/activate"
alias ws-denv="deactivate"

# Networking
alias ws-ipShow="hostname -I | awk '{print \$1}'"
alias ws-goLive='python3 -m http.server $1'
alias ws-portCheck='nmap localhost'
